### ISSUE TITLE
pip install 시에 UnicodeDecodeError 발생. open readme.rst 에 encoding 추가해 주세요.

### ISSUE THREAD

**Issue by daewonyoon** [youknowone/hangul-romanize#1]
```
 with open('README.rst') as f:
```

setup.py 의 README.rst 여는 부분에 encoding 이 지정되지 않아서, 윈도우에서 설치할 때, `UnicodeDecodeError` 가 발생합니다.

**Comment by youknowone** [comment]
수정해서 새로 배포했습니다 https://pypi.org/project/hangul-romanize/0.1.0/
